### ISSUE TITLE
Django 1.8 error: ImportError: cannot import name add_to_builtins

### ISSUE THREAD

**Issue by Nekmo** [jezdez/django-hosts#31]
The version of Pypi is not working in Django 1.8. An error occurs trying to import:

      File "/home/nekmo/.virtualenvs/xxxx/local/lib/python2.7/site-packages/django_hosts/apps.py", line 4, in <module>
        from django.template import add_to_builtins
    ImportError: cannot import name add_to_builtins

Please, update Pypi repo.

**Comment by Nekmo** [comment]
Pypi version is outdated?

**Comment by AliHichem** [comment]
same here

**Comment by seanbrant** [comment]
Master has a fix for this [1]. Any chance someone can push a new release to pypi with this fix?

[1] https://github.com/jezdez/django-hosts/blob/master/django_hosts/apps.py#L6
